### PR TITLE
Added easy enter box

### PR DESCRIPTION
**Pull request by MallocByte**
So you don't need to edit the url to join a game

### CODE REVIEW

**Review by DusterTheFirst — CHANGES_REQUESTED** [review]
does not add any accessability, editing the url is just as easy

**Comment by MallocByte** [comment]
Well actually it does help because people that haven't used the site b4 would rather just enter the code into the box instead of editing the url

**Comment by DusterTheFirst** [comment]
or would they?

**Comment by TheFallingPie** [comment]
but what if they cant code

**Review by ghost — CHANGES_REQUESTED** [review]
It should be a box below the nickname instead of directly editing the URL
Not to mention that if the hash was changed mid-game, it might seriously mess things up

**Comment by DusterTheFirst** [comment]
We have implemented this feature using the login screen, see dd26e5628bc31fbc292f26b76a32d5b82dcb16e6

**Pull request closed without merging**
