### PR TITLE
This died pretty quickly.

### PR DESCRIPTION
**Pull request by The-Cyber-Patriot**
We can make this game's death official if you want.

### CODE REVIEW

**Comment by DusterTheFirst** [comment]
it is still alive my dude

**Comment by ghost** [comment]
@DusterTheFirst I suggest we merge this because it's been dead for over a year now.
*Or we can revive it.*
I am in on reviving and rewriting it (especially since I know more WebGL now 👍)

**Comment by DusterTheFirst** [comment]
Ok so, here's my stance. I currently have no "development machine". I'm moving stuff around and haven't been able to program since last year. 

I am not 100% against rebooting bicbacboe, but I am also not 100% for it.

BicBacBoe was meant to be a small learning project for client-server communication, especially real-time communication.

From what I have seen and heard, not many people use the program, and I don't know of any way to necessarily change that.

Many times I have thought of ideas to add to the project, but I had no idea how to implement them nor where to put them.

As a final note, I also think the frontend WebGL part might have been over-engineered. The "game" does not require split-second/real-time rendering, nor does it utilize 3d.

Once I am resituated and back in business, yes, I would be up for a newer/cleaner React Typescript frontend as well as a more robust backend (also in TS). This would be a good collaborative project, and I would be able to add more things to the project due to my new knowledge and new circumstances (a lot of the bicbacboe frontend was written on an iPad in school). Below I will list ideas of things to add, and also why I wasn't able to add them if I tried. Feel free to expand the list.

**Ideas**
- Chat
- Tournament style (round robin/brackets)
  - A possibility of a host that can see all games
- [3D tic tac toe (might need GL)](https://en.wikipedia.org/wiki/3D_tic-tac-toe)
- Ultimate Tic tac toe
**[Link for more info on the above](https://github.com/BicBacBoe/client/blob/ce90675208b697c1752543105e1a9f821a7bc905/src/Menu.tsx#L39)**
- Open game finder
- "better" com schema (refinement of packets)
- Resuming games
- Logging in (google/discord/GH/facebook??)
  - Friends?
- Better mobile support

**Closing note**
I would most recommend for my sanity and in order for the project to have me there able to help with it to not start until I am ready. I do appoint myself as the project leader for this project and I hope you understand that you should check with me (through adding to the project's board or in "person") before implementing a feature and that I have full control to deny the implementation into this version/distribution of the game.

**Comment by DusterTheFirst** [comment]
Also, another note. The servers are down cause my whole rig is unplugged downstairs and that includes my pi.

**Pull request closed without merging**
